// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: homework.sql

package db

import (
	"context"
	"time"
)

const createHomework = `-- name: CreateHomework :one
INSERT INTO homeworks (
    teacher_id,
    subject,
    title,
    file_name,
    saved_path
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, teacher_id, subject, title, file_name, saved_path, is_closed, created_at, updated_at, closed_at
`

type CreateHomeworkParams struct {
	TeacherID int64  `json:"teacher_id"`
	Subject   string `json:"subject"`
	Title     string `json:"title"`
	FileName  string `json:"file_name"`
	SavedPath string `json:"saved_path"`
}

func (q *Queries) CreateHomework(ctx context.Context, arg CreateHomeworkParams) (Homework, error) {
	row := q.db.QueryRowContext(ctx, createHomework,
		arg.TeacherID,
		arg.Subject,
		arg.Title,
		arg.FileName,
		arg.SavedPath,
	)
	var i Homework
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.Title,
		&i.FileName,
		&i.SavedPath,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteHomework = `-- name: DeleteHomework :exec
DELETE FROM homeworks
WHERE id = $1
`

func (q *Queries) DeleteHomework(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHomework, id)
	return err
}

const getHomework = `-- name: GetHomework :one
SELECT id, teacher_id, subject, title, file_name, saved_path, is_closed, created_at, updated_at, closed_at FROM homeworks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHomework(ctx context.Context, id int64) (Homework, error) {
	row := q.db.QueryRowContext(ctx, getHomework, id)
	var i Homework
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.Title,
		&i.FileName,
		&i.SavedPath,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listHomework = `-- name: ListHomework :many
SELECT id, teacher_id, subject, title, file_name, saved_path, is_closed, created_at, updated_at, closed_at FROM homeworks
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListHomeworkParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListHomework(ctx context.Context, arg ListHomeworkParams) ([]Homework, error) {
	rows, err := q.db.QueryContext(ctx, listHomework, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Homework{}
	for rows.Next() {
		var i Homework
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Subject,
			&i.Title,
			&i.FileName,
			&i.SavedPath,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeworkByTeacherId = `-- name: ListHomeworkByTeacherId :many
SELECT id, teacher_id, subject, title, file_name, saved_path, is_closed, created_at, updated_at, closed_at FROM homeworks
WHERE teacher_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListHomeworkByTeacherIdParams struct {
	TeacherID int64 `json:"teacher_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListHomeworkByTeacherId(ctx context.Context, arg ListHomeworkByTeacherIdParams) ([]Homework, error) {
	rows, err := q.db.QueryContext(ctx, listHomeworkByTeacherId, arg.TeacherID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Homework{}
	for rows.Next() {
		var i Homework
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Subject,
			&i.Title,
			&i.FileName,
			&i.SavedPath,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHomework = `-- name: UpdateHomework :one
UPDATE homeworks
SET title = $2,
    file_name = $3,
    saved_path = $4,
    is_closed = $5,
    updated_at = $6,
    closed_at = $7
WHERE id = $1
RETURNING id, teacher_id, subject, title, file_name, saved_path, is_closed, created_at, updated_at, closed_at
`

type UpdateHomeworkParams struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	FileName  string    `json:"file_name"`
	SavedPath string    `json:"saved_path"`
	IsClosed  bool      `json:"is_closed"`
	UpdatedAt time.Time `json:"updated_at"`
	ClosedAt  time.Time `json:"closed_at"`
}

func (q *Queries) UpdateHomework(ctx context.Context, arg UpdateHomeworkParams) (Homework, error) {
	row := q.db.QueryRowContext(ctx, updateHomework,
		arg.ID,
		arg.Title,
		arg.FileName,
		arg.SavedPath,
		arg.IsClosed,
		arg.UpdatedAt,
		arg.ClosedAt,
	)
	var i Homework
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.Title,
		&i.FileName,
		&i.SavedPath,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}
