// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type Homework struct {
	ID        int64     `json:"id"`
	TeacherID int64     `json:"teacher_id"`
	Subject   string    `json:"subject"`
	Title     string    `json:"title"`
	FileName  string    `json:"file_name"`
	SavedPath string    `json:"saved_path"`
	IsClosed  bool      `json:"is_closed"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ClosedAt  time.Time `json:"closed_at"`
}

type Message struct {
	ID         int64     `json:"id"`
	FromUserID int64     `json:"from_user_id"`
	ToUserID   int64     `json:"to_user_id"`
	Content    string    `json:"content"`
	IsRead     bool      `json:"is_read"`
	CreatedAt  time.Time `json:"created_at"`
	ReadAt     time.Time `json:"read_at"`
}

type Solution struct {
	ID         int64     `json:"id"`
	ProblemID  int64     `json:"problem_id"`
	UserID     int64     `json:"user_id"`
	FileName   string    `json:"file_name"`
	SavedPath  string    `json:"saved_path"`
	SubmitedAt time.Time `json:"submited_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type User struct {
	ID                int64          `json:"id"`
	Username          sql.NullString `json:"username"`
	HashedPassword    string         `json:"hashed_password"`
	Fullname          sql.NullString `json:"fullname"`
	Email             sql.NullString `json:"email"`
	PhoneNumber       sql.NullString `json:"phone_number"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	CreatedAt         time.Time      `json:"created_at"`
	IsTeacher         sql.NullBool   `json:"is_teacher"`
}
